
import React from 'react';
import { AlertTriangle } from 'lucide-react';

const LegalDisclaimer = () => {
  return (
    <section className="section relative">
      <div className="container-custom relative z-10">
        <div className="max-w-4xl mx-auto glass-card p-8">
          <div className="flex items-start">
            <AlertTriangle className="w-6 h-6 text-hollywood-highlight mr-4 flex-shrink-0 mt-1" />
            <div>
              <h3 className="text-xl font-bold text-white mb-4">Legal Disclaimer</h3>
              <div className="space-y-4 text-white/80 text-sm">
                <p>
                  Screenplay Writer GPT is an AI tool designed to assist in the creation of screenplays. All content generated by this tool is provided "as is" without any warranties, express or implied.
                </p>
                <p>
                  Users are solely responsible for the content they create, modify, or publish using this tool. AI Web Tools LLC does not claim ownership of any content generated by users and bears no responsibility for how such content is used.
                </p>
                <p>
                  While Screenplay Writer GPT aims to create original content, there may be instances of unintentional similarity to existing works. Users are advised to review generated content for potential copyright issues before commercial use.
                </p>
                <p>
                  By using Screenplay Writer GPT, you agree not to use the tool for creating content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.
                </p>
                <p>
                  For any screenplays intended for commercial production, professional legal review is recommended to ensure compliance with copyright laws and other relevant regulations.
                </p>
                <p>
                  This tool utilizes OpenAI's technology and is subject to OpenAI's usage policies and terms of service.
                </p>
              </div>
              <div className="mt-6">
                <div className="flex space-x-4">
                  <a 
                    href="https://openai.com/policies/privacy-policy/" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-hollywood-primary hover:underline text-sm"
                  >
                    Privacy Policy
                  </a>
                  <a 
                    href="https://aiwebtools.ai/terms-of-services" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-hollywood-primary hover:underline text-sm"
                  >
                    Terms of Service
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LegalDisclaimer;
